<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.4</version><relativePath/>
  </parent>
  <groupId>com.ecommerce</groupId><artifactId>ecommerce-platform</artifactId>
  <version>0.0.1-SNAPSHOT</version><packaging>pom</packaging>
  <properties><java.version>17</java.version><springdoc.version>2.8.9</springdoc.version></properties>
  <modules>
    <module>common-library</module><module>iam-service</module><module>user-service</module>
    <module>product-service</module><module>cart-service</module><module>order-service</module>
    <module>payment-service</module><module>notification-service</module>
  </modules>
</project>
