spring:
  application: { name: product-service }
  datasource: { url: jdbc:mysql://localhost:3306/ecommerce_product, username: root, password: root }
  jpa: { hibernate: { ddl-auto: validate }, open-in-view: false }
  elasticsearch: { uris: http://localhost:9200 }
  kafka: { bootstrap-servers: localhost:9092, 
    producer: {
      key-serializer: org.apache.kafka.common.serialization.StringSerializer,
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    },
    consumer: {
      group-id: product-search-consumer,
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer,
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer,
      properties: {
        spring.json.trusted.packages: com.ecommerce.product.event,
        spring.json.value.default.type: com.ecommerce.product.event.ProductEvent
        }
    }}
  flyway: { enabled: true }
server: { port: 8083 }
